### ISSUE TITLE
Freakin meta + backbone (maybe)

### ISSUE THREAD

**Issue by copernicus-mogley** [dloa/alexandria-browser#79]
Priority: https://cdnjs.com/libraries/backbone.js/tutorials/seo-for-single-page-apps/

- [ ] Integrate Backbone.js (http://backbonejs.org/)
- [ ] Use pushstate to redirect social network and search engine user-agents to corresponding view as HTML (https://stackoverflow.com/questions/30897419/what-is-the-use-of-html5-pushstate-in-backbone-history-start-method#30921884)
- [ ] Replace router.js with Backbone.js
- [ ] Replace current view functions with Backbone.js wherever possible
